// USTP CDO Campus Locations - Single source of truth for all location dropdowns
export const USTP_LOCATIONS = [
    "Gymnasium",
    "Cafeteria",
    "Culinary Arts Building",
    "Science Complex Building",
    "Old Civil Engineering Building",
    "Science Centrum",
    "Engineering Complex II",
    "Student Lounge",
    "LRC Building",
    "New Clinic Building",
    "Parking Lot A",
    "Parking Lot B",
    "Engineering Complex I",
    "Gym Lobby",
    "Information and Communication Technology Center",
    "14",
    "Food innovation",
    "53",
    "54",
    "Study Shed",
    "Study Shed 2",
    "Guidance and Testing Center",
    "Arts and Culture Building",
    "Study Shed 3",
    "Study Shed 4",
    "Study Shed 5",
    "Technology Building",
    "Student Center",
    "BTED",
    "Blank",
    "Sports Complex",
    "Dr. Rotoras Memorial Statue",
    "Administration Building",
    "Civil Technology Building (small)",
    "Civil Technology Building (Big)",
    "Sump Pit",
    "Girl's Trade Building",
    "Printing Press",
    "Study Shed 6",
    "ITB Building",
    "SPED Center"
];
